-- Private rotation cursor for the 6-hourly water-temp cron
-- (runWaterTempRefresh): ISO timestamp of the last run that reached a write
-- DECISION for this beach.
--
-- THE NAME IS WIDER THAN THE WRITER. Wave data is bulk-written into KV by the
-- offline NOAA GRIB pipeline, not by any Worker cron. This column stays the
-- water-temp cron's cursor because that cron walks the same beach set on the
-- same cadence; TODO.md tracks retiring the column when the water-temp pass
-- moves offline too.
--
-- WHY IT CANNOT SHARE recompute_updated. runFlagRecompute rewrites
-- recompute_updated to a single shared nowIso for its ENTIRE run's beach set
-- every hour, flattening the column to ~2 distinct values across the table. A
-- cursor a different cron flattens hourly cannot order a cold tier: the sort
-- collapses to id ASC and a fixed tail of rows starves once the table outgrows
-- what one run can finish. Each cron is single-writer of its own cursor column.
--
-- WHO WRITES IT: runWaterTempRefresh only, INCREMENTALLY (batches of
-- WAVE_CURSOR_FLUSH_SIZE as the write pool reaches each beach, never one batch
-- after the loop, which is the thing a wall-clock kill interrupts). Stamped for
-- every beach that reached a write decision, INCLUDING one with no reading at
-- all, which writes no KV: stamping only on a successful write would pin a
-- permanently readingless beach to the head of the queue forever and invert the
-- starvation this column exists to fix. Beaches the run never ATTEMPTED (gather
-- deadline) are NOT stamped, so they sort first next run.
--
-- WHO READS IT: runWaterTempRefresh's own SELECT (ORDER BY ... wave_updated
-- ASC, id ASC) only. It rides along in row objects on the hourly cron and
-- router.js's SELECT *, but nothing on the request path reads it.
--
-- NULL is required (SQLite ADD COLUMN forbids NOT NULL without a DEFAULT) and
-- is also semantically right: NULL sorts first under ASC, so a row enters the
-- rotation at the head with no backfill. Offline discovery's UPSERTs enumerate
-- columns explicitly, so newly discovered rows arrive NULL. No index, matching
-- the precedent that recompute_updated has never been indexed at this row count.
ALTER TABLE beaches ADD COLUMN wave_updated TEXT;
