// Exports the literal text of the inline consumer that keeps a beach detail
// page current between reloads. It runs in the browser, not in the Worker.
//
// On every "swimreport:refresh" (refreshScript.js) it fetches the page's own
// canonical URL, parses the response with DOMParser and reconciles the blocks
// render.js marks with data-refresh="<key>" into the live page. Everything
// outside a keyed block is left alone: the back link and share row the hero
// scripts enhanced, the flag legend, and the page shell.
//
// Two kinds of keyed block. A leaf, one with no keyed descendant, is replaced
// whole when its serialization differs from the one last applied under that
// key, inserted beside its nearest keyed sibling when the page lacked it (an
// official flag newly posted, an advisory raised) and removed when the fresh
// page no longer carries it (the official expired, the advisory lifted). A
// container, one holding keyed blocks, only has its attributes synced (the
// hero's data-flag wash) and its keyed children reconciled; it is never
// inserted or removed, which holds because the hero is on every page. The wave
// map and the webcam are keyed too: they serialize the same on every fetch, so
// their iframes are never rebuilt, and a rotated webcam replaces itself.
//
// A block the visitor is inside, by focus or by a text selection, is left for
// the next tick. An expander they opened stays open across a rebuild, matched
// by its summary. A response that is not a detail page (a 404 after the beach
// was hidden) changes nothing. After a pass the script syncs the tab icon to
// the fresh page's and dispatches "swimreport:refreshed", which is what makes
// waveTicksScript.js relabel a rebuilt tick row.

const SCRIPT_LINES = [
  "(function () {",
  "  if (typeof fetch === 'undefined' || typeof DOMParser === 'undefined') {",
  "    return;",
  "  }",
  "  const KEY = 'data-refresh';",
  "  const SELECTOR = '[' + KEY + ']';",
  "  const url = window.location.pathname;",
  // Serialization of each leaf as last applied, keyed by data-refresh. The seed
  // is taken here, before the kit upgrades any component, so it matches what
  // the same markup serializes to inside a parsed response.
  "  const lastHtml = {};",
  "  const isContainer = function (el) {",
  "    return el.querySelector(SELECTOR) !== null;",
  "  };",
  "  const liveKeyed = function () {",
  "    const map = {};",
  "    const els = document.querySelectorAll(SELECTOR);",
  "    for (let i = 0; i < els.length; i = i + 1) {",
  "      map[els[i].getAttribute(KEY)] = els[i];",
  "    }",
  "    return map;",
  "  };",
  "  const seed = liveKeyed();",
  "  for (const key in seed) {",
  "    if (!isContainer(seed[key])) {",
  "      lastHtml[key] = seed[key].outerHTML;",
  "    }",
  "  }",
  "  const busy = function (el) {",
  "    if (document.activeElement && el.contains(document.activeElement)) {",
  "      return true;",
  "    }",
  "    const sel = typeof window.getSelection === 'function' ? window.getSelection() : null;",
  "    if (sel && !sel.isCollapsed && sel.rangeCount > 0 &&",
  "        el.contains(sel.getRangeAt(0).commonAncestorContainer)) {",
  "      return true;",
  "    }",
  "    return false;",
  "  };",
  // An expander's identity is its summary attribute, or the text of its
  // slotted summary (the alert expander), so it survives the block's rebuild.
  "  const detailsKey = function (details) {",
  "    const summary = details.getAttribute('summary');",
  "    if (summary) {",
  "      return summary;",
  "    }",
  "    const slotted = details.querySelector('[slot=\"summary\"]');",
  "    return slotted ? slotted.textContent : '';",
  "  };",
  "  const carryOpen = function (oldEl, newEl) {",
  "    const open = oldEl.querySelectorAll('wa-details[open]');",
  "    for (let i = 0; i < open.length; i = i + 1) {",
  "      const key = detailsKey(open[i]);",
  "      if (!key) {",
  "        continue;",
  "      }",
  "      const twins = newEl.querySelectorAll('wa-details');",
  "      for (let j = 0; j < twins.length; j = j + 1) {",
  "        if (detailsKey(twins[j]) === key) {",
  "          twins[j].setAttribute('open', '');",
  "        }",
  "      }",
  "    }",
  "  };",
  "  const syncAttributes = function (liveEl, newEl) {",
  "    const stale = [];",
  "    for (let i = 0; i < liveEl.attributes.length; i = i + 1) {",
  "      if (!newEl.hasAttribute(liveEl.attributes[i].name)) {",
  "        stale.push(liveEl.attributes[i].name);",
  "      }",
  "    }",
  "    for (let i = 0; i < stale.length; i = i + 1) {",
  "      liveEl.removeAttribute(stale[i]);",
  "    }",
  "    for (let i = 0; i < newEl.attributes.length; i = i + 1) {",
  "      const name = newEl.attributes[i].name;",
  "      const value = newEl.attributes[i].value;",
  "      if (liveEl.getAttribute(name) !== value) {",
  "        liveEl.setAttribute(name, value);",
  "      }",
  "    }",
  "  };",
  "  const keyedSibling = function (el, direction) {",
  "    let sibling = el[direction];",
  "    while (sibling) {",
  "      if (sibling.hasAttribute(KEY)) {",
  "        return sibling.getAttribute(KEY);",
  "      }",
  "      sibling = sibling[direction];",
  "    }",
  "    return null;",
  "  };",
  // A block the page lacked goes after the nearest preceding keyed sibling the
  // page has, else before the nearest following one. Neither present means its
  // parent is not on the page either, and the block waits for a reload.
  "  const insertNew = function (newEl, live) {",
  "    const imported = document.importNode(newEl, true);",
  "    const prev = keyedSibling(newEl, 'previousElementSibling');",
  "    if (prev !== null && live[prev]) {",
  "      live[prev].after(imported);",
  "      return imported;",
  "    }",
  "    const next = keyedSibling(newEl, 'nextElementSibling');",
  "    if (next !== null && live[next]) {",
  "      live[next].before(imported);",
  "      return imported;",
  "    }",
  "    return null;",
  "  };",
  "  const apply = function (doc) {",
  "    const live = liveKeyed();",
  "    const fresh = doc.querySelectorAll(SELECTOR);",
  "    const seen = {};",
  "    for (let i = 0; i < fresh.length; i = i + 1) {",
  "      const newEl = fresh[i];",
  "      const key = newEl.getAttribute(KEY);",
  "      seen[key] = true;",
  "      const liveEl = live[key];",
  "      if (isContainer(newEl)) {",
  "        if (liveEl) {",
  "          syncAttributes(liveEl, newEl);",
  "        }",
  "        continue;",
  "      }",
  "      const html = newEl.outerHTML;",
  "      if (!liveEl) {",
  "        const inserted = insertNew(newEl, live);",
  "        if (inserted) {",
  "          live[key] = inserted;",
  "          lastHtml[key] = html;",
  "        }",
  "        continue;",
  "      }",
  "      if (html === lastHtml[key] || busy(liveEl)) {",
  "        continue;",
  "      }",
  "      const imported = document.importNode(newEl, true);",
  "      carryOpen(liveEl, imported);",
  "      liveEl.replaceWith(imported);",
  "      live[key] = imported;",
  "      lastHtml[key] = html;",
  "    }",
  "    for (const key in live) {",
  "      if (!seen[key] && !isContainer(live[key]) && !busy(live[key])) {",
  "        live[key].remove();",
  "        delete lastHtml[key];",
  "      }",
  "    }",
  "  };",
  "  const syncIcon = function (doc) {",
  "    const icon = document.querySelector('link[rel=\"icon\"]');",
  "    const next = doc.querySelector('link[rel=\"icon\"]');",
  "    if (icon && next && icon.getAttribute('href') !== next.getAttribute('href')) {",
  "      icon.setAttribute('href', next.getAttribute('href'));",
  "    }",
  "  };",
  "  let inflight = false;",
  "  document.addEventListener('swimreport:refresh', function () {",
  "    if (inflight) {",
  "      return;",
  "    }",
  "    inflight = true;",
  "    fetch(url, { cache: 'no-cache' }).then(function (res) {",
  "      if (!res.ok) {",
  "        throw new Error('unexpected status ' + res.status);",
  "      }",
  "      return res.text();",
  "    }).then(function (html) {",
  "      const doc = new DOMParser().parseFromString(html, 'text/html');",
  "      if (!doc.querySelector('main.detail-main')) {",
  "        throw new Error('not a detail page');",
  "      }",
  "      apply(doc);",
  "      syncIcon(doc);",
  "      document.dispatchEvent(new CustomEvent('swimreport:refreshed'));",
  "    }).catch(function (err) {",
  "      console.log('detail refresh failed: ' + err.message);",
  "    }).then(function () {",
  "      inflight = false;",
  "    });",
  "  });",
  "})();"
];

export const DETAIL_REFRESH_SCRIPT = SCRIPT_LINES.join("\n");
