// src/marineZones.js — offline nearest-marine-zone resolution against the
// repo-committed NWS coastal marine zone geometry
// (data/marine-zones-greatlakes.json, generated by scripts/build-marine-zones.js
// from the ~biannual shapefile release at https://www.weather.gov/gis/MarineZones).
//
// This module replaces the retired in-Worker runMarineEnrichment cron, which
// resolved each beach's adjacent marine zone by probing
// api.weather.gov/zones?type=marine at widening offshore rings (up to 17 live
// requests per beach). Here the same answer is pure local math: point-in-polygon
// first, then nearest-polygon-EDGE within a 15 km cap. Beach coordinates sit on
// LAND while marine polygons cover WATER, so PIP alone almost always misses —
// nearest-edge is the offline equivalent of the online probe's widening rings.
// The 15 km cap is a strict superset of the retired probe's maximum reach (the
// 0.10-degree diagonal ring is ~13.6 km at Great Lakes latitudes), so no beach
// the probe could resolve becomes unresolvable.
//
// Pure: no fetch, no Date, no Worker imports. Imported ONLY by the offline
// batch (scripts/discovery-batch.js) and tests — never by src/index.js. The
// request path never touches this module; the two-path rule is unchanged.
//
// Distance metric: per ring segment, point-to-segment distance in a local
// equirectangular projection anchored at the beach point
// (x = dLon * cos(beachLat) * 111.195 km, y = dLat * 111.195 km); the error is
// negligible at <= 15 km. Holes are kept and their edges count — an island
// beach (Apostle Islands, Mackinac) sits inside a HOLE of a marine polygon and
// correctly resolves via the nearest hole edge.
//
// Tie-breaking is fully deterministic: smallest distance wins; exact ties
// (< 1e-9 km, e.g. a point equidistant from two adjacent zones' shared
// boundary) go to the lexicographically smallest zone id. Deterministic
// resolution + change-only SQL in the batch means steady-state runs emit zero
// marine statements.

import { pointInGeometry } from "./geo.js";

export const MARINE_ZONE_MAX_DISTANCE_KM = 15;

// Kilometres per degree of latitude (and of longitude at the equator) on the
// spherical earth used across src/geo.js: 2 * pi * 6371 / 360.
const KM_PER_DEG = 111.195;

// Exact-tie epsilon for the deterministic tie-break (kilometres).
const TIE_EPSILON_KM = 1e-9;

// Validates the parsed data/marine-zones-greatlakes.json shape and precomputes,
// per zone: a GeoJSON MultiPolygon wrapper for pointInGeometry, and a bounding
// box expanded by the distance cap (in degrees) so nearestMarineZone can skip
// zones that cannot possibly be within reach. Throws on malformed input — the
// data file is repo-committed, so a malformed file is a build/commit bug that
// must fail the batch loudly, not resolve every beach to null.
export function buildMarineZoneIndex(zonesData) {
  if (zonesData === null || typeof zonesData !== "object" || !Array.isArray(zonesData.zones)) {
    throw new Error("marine zones data: expected { zones: [...] }");
  }
  const zones = [];
  for (const zone of zonesData.zones) {
    if (zone === null || typeof zone !== "object" ||
      typeof zone.id !== "string" || zone.id === "" ||
      !Array.isArray(zone.polygons) || zone.polygons.length === 0) {
      throw new Error("marine zones data: malformed zone entry" +
        (zone && typeof zone.id === "string" ? " " + zone.id : ""));
    }
    let minLon = Infinity;
    let minLat = Infinity;
    let maxLon = -Infinity;
    let maxLat = -Infinity;
    for (const polygon of zone.polygons) {
      if (!Array.isArray(polygon) || polygon.length === 0) {
        throw new Error("marine zones data: malformed polygon in zone " + zone.id);
      }
      for (const ring of polygon) {
        if (!Array.isArray(ring) || ring.length < 4) {
          throw new Error("marine zones data: malformed ring in zone " + zone.id);
        }
        for (const pt of ring) {
          if (!Array.isArray(pt) || pt.length < 2 ||
            typeof pt[0] !== "number" || !isFinite(pt[0]) ||
            typeof pt[1] !== "number" || !isFinite(pt[1])) {
            throw new Error("marine zones data: malformed point in zone " + zone.id);
          }
          if (pt[0] < minLon) { minLon = pt[0]; }
          if (pt[0] > maxLon) { maxLon = pt[0]; }
          if (pt[1] < minLat) { minLat = pt[1]; }
          if (pt[1] > maxLat) { maxLat = pt[1]; }
        }
      }
    }
    // Expand the bbox by the cap. Longitude degrees shrink with latitude, so
    // use the cosine at the bbox latitude CLOSEST TO THE POLE (smallest cos =
    // widest pad) — the bbox may only ever over-include, never exclude a point
    // actually within the cap.
    const latPadDeg = MARINE_ZONE_MAX_DISTANCE_KM / KM_PER_DEG;
    const maxAbsLatRad = Math.max(Math.abs(minLat), Math.abs(maxLat)) * Math.PI / 180;
    const cosLat = Math.max(Math.cos(maxAbsLatRad + latPadDeg * Math.PI / 180), 0.01);
    const lonPadDeg = MARINE_ZONE_MAX_DISTANCE_KM / (KM_PER_DEG * cosLat);
    zones.push({
      id: zone.id,
      geometry: { type: "MultiPolygon", coordinates: zone.polygons },
      bbox: {
        minLon: minLon - lonPadDeg,
        minLat: minLat - latPadDeg,
        maxLon: maxLon + lonPadDeg,
        maxLat: maxLat + latPadDeg
      }
    });
  }
  return { zones: zones };
}

// Squared distance (km^2 avoided — plain km) from the origin (the beach point,
// already projected to 0,0) to the segment a-b in the local projection.
function pointToSegmentKm(ax, ay, bx, by) {
  const dx = bx - ax;
  const dy = by - ay;
  const len2 = dx * dx + dy * dy;
  let t = 0;
  if (len2 > 0) {
    // Project the origin onto the segment, clamped to [0, 1].
    t = -(ax * dx + ay * dy) / len2;
    if (t < 0) { t = 0; }
    if (t > 1) { t = 1; }
  }
  const px = ax + t * dx;
  const py = ay + t * dy;
  return Math.sqrt(px * px + py * py);
}

// Minimum distance (km) from (lat, lon) to any ring edge of the zone —
// OUTER RINGS AND HOLES ALIKE (see the island-in-a-hole note above).
function minEdgeDistanceKm(zone, lat, lon) {
  const cosLat = Math.cos(lat * Math.PI / 180);
  let best = Infinity;
  for (const polygon of zone.geometry.coordinates) {
    for (const ring of polygon) {
      for (let i = 0; i < ring.length - 1; i = i + 1) {
        const ax = (ring[i][0] - lon) * cosLat * KM_PER_DEG;
        const ay = (ring[i][1] - lat) * KM_PER_DEG;
        const bx = (ring[i + 1][0] - lon) * cosLat * KM_PER_DEG;
        const by = (ring[i + 1][1] - lat) * KM_PER_DEG;
        const d = pointToSegmentKm(ax, ay, bx, by);
        if (d < best) { best = d; }
      }
    }
  }
  return best;
}

// Resolve the marine zone for a beach point: the zone containing the point
// (distance 0), else the zone with the nearest edge within
// MARINE_ZONE_MAX_DISTANCE_KM, else null. Non-finite/non-number lat/lon -> null.
export function nearestMarineZone(index, lat, lon) {
  if (typeof lat !== "number" || !isFinite(lat) ||
    typeof lon !== "number" || !isFinite(lon)) {
    return null;
  }
  let bestId = null;
  let bestDist = Infinity;
  for (const zone of index.zones) {
    const b = zone.bbox;
    if (lon < b.minLon || lon > b.maxLon || lat < b.minLat || lat > b.maxLat) {
      continue;
    }
    let dist;
    if (pointInGeometry(zone.geometry, lat, lon)) {
      dist = 0;
    } else {
      dist = minEdgeDistanceKm(zone, lat, lon);
    }
    if (bestId === null ||
      dist < bestDist - TIE_EPSILON_KM ||
      (Math.abs(dist - bestDist) <= TIE_EPSILON_KM && zone.id < bestId)) {
      bestId = zone.id;
      bestDist = dist;
    }
  }
  if (bestId === null || bestDist > MARINE_ZONE_MAX_DISTANCE_KM) {
    return null;
  }
  return bestId;
}
