// src/marineZones.js — offline nearest-marine-zone resolution against the
// repo-committed NWS coastal marine zone geometry
// (data/marine-zones.json, generated by scripts/build-marine-zones.js
// from the ~biannual shapefile release at https://www.weather.gov/gis/MarineZones).
//
// Resolution is point-in-polygon first, then nearest-polygon-edge within a 15 km
// cap. Beach coordinates sit on land while marine polygons cover water, so
// point-in-polygon alone almost always misses and the nearest-edge pass is what
// actually resolves a beach. 15 km is comfortably wider than the ~13.6 km a
// beach's adjacent zone sits offshore at Great Lakes latitudes.
//
// Pure: no fetch, no Date, no Worker imports. Imported only by the offline batch
// (scripts/discovery-batch.js) and tests, never by src/index.js.
//
// Distance metric: per ring segment, point-to-segment distance in a local
// equirectangular projection anchored at the beach point
// (x = dLon * cos(beachLat) * 111.195 km, y = dLat * 111.195 km); the error is
// negligible at <= 15 km. Holes are kept and their edges count — an island
// beach (Apostle Islands, Mackinac) sits inside a HOLE of a marine polygon and
// correctly resolves via the nearest hole edge.
//
// Tie-breaking is deterministic: smallest distance wins, and an exact tie
// (< 1e-9 km, a point equidistant from two adjacent zones' shared boundary) goes
// to the lexicographically smallest zone id. That plus change-only SQL in the
// batch means a steady-state run emits zero marine statements.

import { pointInGeometry, minEdgeDistanceKm, KM_PER_DEG } from "./geo.js";

export const MARINE_ZONE_MAX_DISTANCE_KM = 15;

// Exact-tie epsilon for the deterministic tie-break (kilometres).
const TIE_EPSILON_KM = 1e-9;

// Validates the parsed data/marine-zones.json shape and precomputes,
// per zone: a GeoJSON MultiPolygon wrapper for pointInGeometry, and a bounding
// box expanded by the distance cap (in degrees) so nearestMarineZone can skip
// zones that cannot possibly be within reach. Throws on malformed input — the
// data file is repo-committed, so a malformed file is a build/commit bug that
// must fail the batch loudly, not resolve every beach to null.
export function buildMarineZoneIndex(zonesData) {
  if (zonesData === null || typeof zonesData !== "object" || !Array.isArray(zonesData.zones)) {
    throw new Error("marine zones data: expected { zones: [...] }");
  }
  const zones = [];
  for (const zone of zonesData.zones) {
    if (zone === null || typeof zone !== "object" ||
      typeof zone.id !== "string" || zone.id === "" ||
      !Array.isArray(zone.polygons) || zone.polygons.length === 0) {
      throw new Error("marine zones data: malformed zone entry" +
        (zone && typeof zone.id === "string" ? " " + zone.id : ""));
    }
    let minLon = Infinity;
    let minLat = Infinity;
    let maxLon = -Infinity;
    let maxLat = -Infinity;
    for (const polygon of zone.polygons) {
      if (!Array.isArray(polygon) || polygon.length === 0) {
        throw new Error("marine zones data: malformed polygon in zone " + zone.id);
      }
      for (const ring of polygon) {
        if (!Array.isArray(ring) || ring.length < 4) {
          throw new Error("marine zones data: malformed ring in zone " + zone.id);
        }
        for (const pt of ring) {
          if (!Array.isArray(pt) || pt.length < 2 ||
            typeof pt[0] !== "number" || !isFinite(pt[0]) ||
            typeof pt[1] !== "number" || !isFinite(pt[1])) {
            throw new Error("marine zones data: malformed point in zone " + zone.id);
          }
          if (pt[0] < minLon) { minLon = pt[0]; }
          if (pt[0] > maxLon) { maxLon = pt[0]; }
          if (pt[1] < minLat) { minLat = pt[1]; }
          if (pt[1] > maxLat) { maxLat = pt[1]; }
        }
      }
    }
    // Expand the bbox by the cap. Longitude degrees shrink with latitude, so
    // use the cosine at the bbox latitude CLOSEST TO THE POLE (smallest cos =
    // widest pad) — the bbox may only ever over-include, never exclude a point
    // actually within the cap.
    const latPadDeg = MARINE_ZONE_MAX_DISTANCE_KM / KM_PER_DEG;
    const maxAbsLatRad = Math.max(Math.abs(minLat), Math.abs(maxLat)) * Math.PI / 180;
    const cosLat = Math.max(Math.cos(maxAbsLatRad + latPadDeg * Math.PI / 180), 0.01);
    const lonPadDeg = MARINE_ZONE_MAX_DISTANCE_KM / (KM_PER_DEG * cosLat);
    zones.push({
      id: zone.id,
      geometry: { type: "MultiPolygon", coordinates: zone.polygons },
      bbox: {
        minLon: minLon - lonPadDeg,
        minLat: minLat - latPadDeg,
        maxLon: maxLon + lonPadDeg,
        maxLat: maxLat + latPadDeg
      }
    });
  }
  return { zones: zones };
}

// Resolve the marine zone for a beach point: the zone containing the point
// (distance 0), else the zone with the nearest edge within
// MARINE_ZONE_MAX_DISTANCE_KM, else null. Non-finite/non-number lat/lon -> null.
export function nearestMarineZone(index, lat, lon) {
  if (typeof lat !== "number" || !isFinite(lat) ||
    typeof lon !== "number" || !isFinite(lon)) {
    return null;
  }
  let bestId = null;
  let bestDist = Infinity;
  for (const zone of index.zones) {
    const b = zone.bbox;
    if (lon < b.minLon || lon > b.maxLon || lat < b.minLat || lat > b.maxLat) {
      continue;
    }
    let dist;
    if (pointInGeometry(zone.geometry, lat, lon)) {
      dist = 0;
    } else {
      // Shared with the ECCC clients (src/geo.js). buildMarineZoneIndex has
      // already validated every ring/point, so the shared helper's defensive
      // skips can never fire on this path — malformed data still throws there.
      dist = minEdgeDistanceKm(zone.geometry, lat, lon);
    }
    if (bestId === null ||
      dist < bestDist - TIE_EPSILON_KM ||
      (Math.abs(dist - bestDist) <= TIE_EPSILON_KM && zone.id < bestId)) {
      bestId = zone.id;
      bestDist = dist;
    }
  }
  if (bestId === null || bestDist > MARINE_ZONE_MAX_DISTANCE_KM) {
    return null;
  }
  return bestId;
}
